export enum RouteName {
    Login = 'login',
    Setup = 'setup',
    Dashboard = 'dashboard',
    Pages='pages',
    About = 'about',
    Projects = 'projects',
    Stack = 'stack',
    Analyze = 'analyze',
    Setting = 'setting',
    UserSetting = 'user-setting',
    Home = 'home',
    User = 'user',
    Post = 'post',
    ListProject = 'project-list',
    EditProject = 'project-edit',
    ListAbout = 'about-list',
    EditAbout = 'about-edit',
    List = 'list',
    Edit = 'edit',
}
